rolldown/tsdown

.github/workflows/tests.yml

The `build` step for `pkg-pr-new` continuous release workflow was deleted incorrectly in https://github.com/rolldown/tsdown/pull/105. This causes the published package (e.g. `npm i https://pkg.pr.new/tsdown@6c954c5`) not contains `dist/`.

ci: build before pkg-pr-new publish

---

docs/.vitepress/config/theme.ts

Adjusted the right-side navigation in the Chinese documentation to enable quick anchor point jumps. @sxzz

fix: zh-cn config-options outline level

---

docs/.vitepress/components/HomePage.vue

The VoidZero logo is not shown correctly in light mode but in dark mode.
This PR:
• removed the computed ‎`voidZeroLogo` logic from the Vue component.
• replaced the ‎`<img>` tag with a styled ‎`<a>` element using a ‎`.voidzero` class.
• added CSS rules to apply the correct background image for both light and dark themes.

docs: show the corresponding SVG for the `VoidZero` in dark/light mode

---

docs/vite.config.ts

I think it would be nice if `tsdown.config.ts` file have a special icon.

docs: add tsdown icon

---

src/features/watch.ts

When `outDir` is an empty string, the project root directory is added to the ignored list, which will invalidate the watch.

fix: watch mode outDir cannot be an empty string

---

src/features/publint.ts
src/index.ts

I found some issues in `ota-meshi/typescript-eslint-parser-for-extra-files`'s dts output, so I'm migrating it to tsdown.
It uses Yarn@1 ☹️ so I tried to pass `{ pack: "npm" }` to the publint parameter, but it didn't work.
This wires it up.
I wrote #168 in trying to write a repro for it. :)
Didn't see any existing tests, so I didn't add any new ones.

fix: wire up publint options

---

src/features/node-protocol.ts
src/index.ts
src/options.ts
src/plugin/node-protocol.ts
src/plugins.ts
tests/__snapshots__/remove-node-protocol.snap.md
tests/index.test.ts

fix:https://github.com/rolldown/tsdown/issues/176
@sxzz the script needs to update the document,，
In addition, I created a new plugins file, and I'm going to move it to plugins in the next pr, which will be clearer. What do you think?

feat(node-protocol): add option to remove the `node:` protocol

---

src/features/target.ts

When I package with tsdown `v0.11.0-beta.1`, I get the following error:
```bash
➜  tsdown-test pnpm tsdown
ℹ tsdown v0.11.0-beta.1 powered by rolldown v1.0.0-beta.8-commit.852c603
ERROR  Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/tsdown-test/node_modules/.pnpm/tsdown@0.11.0-beta.1_typescript@5.8.3/node_modules/semver/ranges/min-version' imported from /Users/tsdown-test/node_modules/.pnpm/tsdown@0.11.0-beta.1_typescript@5.8.3/node_modules/tsdown/dist/index.js
Did you mean to import "semver/ranges/min-version.js"?
at finalizeResolution (node:internal/modules/esm/resolve:275:11)
at moduleResolve (node:internal/modules/esm/resolve:860:10)
at defaultResolve (node:internal/modules/esm/resolve:984:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:719:12)
at …
```

fix: `semver/ranges/min-version` module not found

---

src/features/clean.ts
src/utils/general.ts

When `clean` is the default (`true`), it will be assigned with `dist`, whereas in the current behavior, `dist` is resolved to an absolute path before it is assigned to `clean`, and the `glob` is set to `cwd` in `cleanOutDir`, which results in the `glob` getting an empty list of paths, leading to no files being cleaned.

fix: `clean: true` not work in Windows

---

src/features/clean.ts
src/features/watch.ts
src/index.ts
src/options.ts

If outDir is an empty string, the current logic will clear all files in the root directory of the current project, resulting in a build error.
https://github.com/rolldown/tsdown/blob/3630a61e7c961370b46d71861fceb2f0ea704b4d/src/index.ts#L64-L66

fix: outDir cannot be an empty string

---

pnpm-lock.yaml
pnpm-workspace.yaml

upgrade rolldown dependency version to latest canary to include https://github.com/rolldown/rolldown/commit/8ac92a4ecfb9fbc328033f936d6aac98c22af0ff which allows for working on https://github.com/rolldown/tsdown/issues/162
It is now possible to use custom loaders, but that ticket should remain open until migration docs / helper are updated as well

feat: upgrade rolldown

---

package.json
tsdown.config.ts

When you run the following command in a Yarn PnP environment:
```sh
yarn tsdown index.ts --dts
```
we get the following error:
In a Yarn PnP environment, using the `--dts` flag during build causes a peer dependency error. This is required by `rolldown-plugin-dts`.
Although `typescript` is specified as a peer dependency in `rolldown-plugin-dts`, it's bundled within `tsdown`, so if you use only `tsdown`, the peer dependency is not propagated. Therefore, `tsdown` also needs to declare `typescript` as a peer dependency.

fix(pnp): resolve typescript peer dependency with Yarn PnP

---

src/options/index.ts

When we simply set `workspace: true` , it should allow the root directory of the workspace to not be the package to be bundled.

fix: skip when workspace config has no entry files

---

src/index.ts
src/options/types.ts

This PR solves the problem of handling processes that need to be aborted, like custom Bun.spawn or process spawning logic in `onSuccess`. It solves this by switching out the `p.kill` of `tinyexec` for an Abort Controller. 
Additionally the signal from the `AbortController` is provided as the second argument in the `onSuccess` function definition so that it may be used in the callback.
N/A
N/A

feat: onSuccess Abort Controller

---

src/features/external.ts

If the regular expression passed in carries the `g` modifier, multiple tests may produce unexpected results.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

fix: regexp needs to reset lastIndex each time test is called

---

pnpm-lock.yaml
pnpm-workspace.yaml
src/features/output.ts
src/index.ts
src/options/index.ts
src/options/types.ts
tests/__snapshots__/banner-and-footer-option.snap.md
tests/index.test.ts
tests/utils.ts

Hello. I'm an enthusiast of tsup and have great interest in the tsdown project.
This PR is merely a suggestion and I submitted it with the intention of having a discussion with you.
If this PR doesn't align with the direction of tsdown, please feel free to close it.
tsdown is a project inspired by tsup, and in fact, many of its configuration structures and core philosophies are designed similarly.
For that reason, tsup users who switch to tsdown inevitably expect a similar developer experience (DX).
I believe the banner and footer features fall within that context. These are widely used in various bundlers such as Rollup, esbuild, and webpack, and have been supported in tsup as well.
However, since tsdown currently uses rolldown internally, although the functionality itself is easy to …

feat: add banner, footer options

---

src/config.ts

When using `defineConfig({})`, the return value cannot be spread because the type includes a function. Since the `defineConfig()` is just the identity function, it might be better to keep the type as is. Another option is to create an overload function
The current workaround is to use `satisfies UserOptions`

fix(types): keep type of options

---

docs/.vitepress/components/HomePage.vue

fix(docs): add responsive styles for sponsor SVG on mobile
Add `:deep(svg)` styles to prevent sponsor section overflow on mobile devices. The SVG is injected
via `v-html` and requires deep selector to apply styles.
-
Minimal CSS-only fix without additional markup changes.

fix(docs): add responsive styles for sponsor SVG on mobile

---

src/options/types.ts

Clarifies the documentation for the name option.
Now explicitly states that the name will default to the package name from package.json only in workspace mode, and must be set manually in non-workspace mode for it to appear in the CLI output.
https://github.com/rolldown/tsdown/issues/386
none

docs: clarify behavior of `name` option

---

src/cli.ts
src/index.ts
src/options/config.ts

Wasn't sure how to correctly implement this one, it pretty much implies to load the config file before logging anything, that makes logging a bit annoying at the beginning of the process.
Resolves #359

feat: support silent as programmatic usage

---

docs/.vitepress/config/theme.ts
docs/.vitepress/i18n/translate-map.ts
docs/recipes/react-support.md
docs/recipes/vue-support.md

Adds a "React Support" page.
Also modified the "Vue Support" page to use `create-tsdown` instead of pointing to the starter repo.
Closes #324

docs: add react support page

---

src/features/exports.ts
src/options/index.ts
src/options/types.ts
tests/__snapshots__/dts-enabled-when-exports-types-exists.snap.md
tests/__snapshots__/dts-not-enabled-when-exports-is-string-instead-of-object.snap.md
tests/__snapshots__/dts-not-enabled-when-no-types-field-and-no-exports-types.snap.md
tests/index.test.ts

This PR enables automatic dts (declaration file) generation when exports.types or exports["."].types fields are
present in package.json, extending the existing auto-detection logic that only checked for top-level types and
typings fields. 
Implementation:
- Added hasExportsTypes() helper function to check for exports.types and exports["."].types
- Modified the dts auto-detection logic in resolveConfig() to include the new check
- Maintained backward compatibility - all existing behavior continues to work
Fixes #439 
Created files `tests/__snapshots__/dts-enabled-when-exports-types-exists.snap.md`, `tests/__snapshots__/dts-not-enabled-when-no-types-field-and-no-exports-types.snap.md`, and `tests/__snapshots__/dts-not-enabled-when-exports-is-string-instead-of-object.snap.md`

feat: enable dts if exports.types exists

---

docs/recipes/react-support.md

fixes #446 
This PR fixes a documentation error in the React Support section where the code example incorrectly used export instead of import.
The documentation says "And import it in your entry file:", but the code example incorrectly showed:
```ts
export { MyButton } from './MyButton'
```

docs: fix code example from export to import in React Support section

---

src/options/index.ts

This PR ensures that a proper error is displayed when an invalid `resolve.alias` is set in Vite Config.

fix(options): correct Vite alias handling
