- src/cli.ts
- src/index.ts
- src/options.ts
add sourcemap option for output
https://github.com/rolldown/rolldown/blob/a2bb2cae97e0f79f712c8ff68d116366ee4ecf35/packages/rolldown/src/options/output-options.ts#L28-L32
> feat: add sourcemap option

- src/cli.ts
- src/index.ts
- src/options.ts
Add minify option for output
https://github.com/rolldown/rolldown/blob/a2bb2cae97e0f79f712c8ff68d116366ee4ecf35/packages/rolldown/src/options/output-options.ts#L48
>  feat: add minify option

- src/cli.ts
- src/index.ts
- src/options.ts
add `silent` option just like `tsup` has
> feat: add silent option

- src/options.ts
https://github.com/rolldown/rolldown/blob/b20293d653010b1744177d829bbd74c9b23ca986/packages/rolldown/src/options/input-options.ts#L62-L68
rolldown has browser option, so I added
> feat: add `browser` option to platform

- README.md
Hi !
It can be obvious if you're already into building tools, but I missed a basic example of how to use tsdown (specially since there's still no documentation).
"Install", "Configuration" and "Usage" sections could also be merged into a single "Installation" section, using bullet points for each part.
> chore: add usage information in readme [ci skip]

- docs/reference/cli.md
- docs/zh-CN/reference/cli.md
add missing links in `cli` pages.
> chore: add missing content in `cli.md`

- docs/guide/config-file.md
Fix a tiny typo in the config example of `config-file.md`
N/A
N/A
> docs: correct spelling of 'platform' in configuration examples

- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/index.ts
- tests/__snapshots__/basic.snap.md
- tests/__snapshots__/bundle-dts.snap.md
- tests/__snapshots__/cjs-interop.snap.md
- tests/__snapshots__/custom-extension.snap.md
- tests/__snapshots__/esm-import.snap.md
- tests/__snapshots__/fixed-extension.snap.md
- tests/__snapshots__/noExternal.snap.md
- tests/__snapshots__/resolve-dependency-for-dts.snap.md
- tests/__snapshots__/resolve-paths-in-tsconfig.snap.md
- tests/__snapshots__/syntax-lowering.snap.md
This PR refactors the code to align with the updated `transformPlugin` interface, fixing a panic issue caused by the outdated plugin usage.
https://github.com/rolldown/rolldown/issues/4203
> refactor: adapt to the new `transformPlugin` usage

- src/index.ts
Make build times more visible in the output.
> chore: make build times visible

- .prettierignore
When running `pnpm format`, the files in the snapshot will be formatted, causing the test to fail.
> chore: add `.prettierignore`

- pnpm-workspace.yaml
The preinstall and postinstall scripts for both `rolldown` and `unrs-resolver` can be disabled.
> chore: add `rolldown`/`unrs-resolver` to ignoredBuiltDependencies

- docs/reference/cli.md
- docs/zh-CN/reference/cli.md
- src/cli.ts
- src/index.ts
- src/options.ts
- tests/__snapshots__/env-flag.snap.md
- tests/index.test.ts
Support compile-time env in command-line tool
Resolved #138
> feat(cli): support compile-time env

- src/features/clean.ts
when cleaning, delete the relevant folders while keeping the top-level folders intact.
before
after
> feat: when cleaning, delete the relevant folders

- src/features/node-protocol.ts
ref https://rolldown.rs/guide/plugin-development#plugin-hook-filters
> refactor(node-protocol): use filter property

- docs/reference/config-options.md
- docs/reference/type-aliases/Format.md
- docs/reference/type-aliases/Sourcemap.md
- docs/zh-CN/reference/config-options.md
- docs/zh-CN/reference/type-aliases/Format.md
- docs/zh-CN/reference/type-aliases/Sourcemap.md
- src/options.ts
As the title says.
None.
None.
> docs: add missing default value docs in options interface

- docs/.vitepress/config/theme.ts
- docs/.vitepress/i18n/translate-map.ts
- docs/guide/faq.md
- docs/zh-CN/guide/faq.md
Add a FAQ page, to anwser common questions about tsdown.
Appart from the original question about stub mode, I added some ideas for common questions, It's up to you to keep them or not.
Also, you'll need to translate the chinese version ahah, I only speak english and french 🥖🇫🇷
closes #164, closes #127 (we can also delete the [127-built-in-stubbing](https://github.com/rolldown/tsdown/tree/127-built-in-stubbing) branch).
N/A
> docs: add faq page

- docs/guide/faq.md
- docs/zh-CN/guide/faq.md
The watch-mode link in chinese version was pointing to the english page
N/A
N/A
> docs: fix faq watch-mode link in chinese version

- docs/vite.config.ts
- src/index.ts
> chroe: remove any unnecessary

- tests/__snapshots__/-216.snap.md
- tests/issues.test.ts
This PR adds a test case for #216 
#216 
N/A
> test: add test case for issue 216

- src/options.ts
This PR corrects the link in jsdoc for option `target`.
None.
Docs need to be updated.
> fix: correct option `target` link in jsdoc

- docs/reference/cli.md
- docs/zh-CN/reference/cli.md
- src/cli.ts
- src/features/watch.ts
- src/options/index.ts
Synchronize tsup related configuration https://tsup.egoist.dev/#watch-mode
> feat: add `ignore-watch` option

- .vscode/settings.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Fixed documentation build errors noted in https://app.netlify.com/projects/tsdown/deploys/682b3101d65d1600086495fb
> fix: 🚑 fix failing docs build

- src/features/entry.ts
- src/options/types.ts
Automatically use `src/index.ts` as default entry when no entry is specified.
> feat: automatically use src/index.ts as default entry when no entry is specified

- docs/.vitepress/config/index.ts
fixes #293 
Add Russian language option that redirects to tsdown.ru, where the community-maintained translation of the documentation is hosted. This provides Russian-speaking users with access to localized documentation while maintaining separation from the main repository.
> Add Russian locale with community translation link

- tests/__snapshots__/issues/286.snap.md
- tests/issues.test.ts
- vitest.config.ts
1. Add a test case for https://github.com/rolldown/tsdown/issues/286 
2. Update rolldown-plugin-dts to fix the bug
https://github.com/rolldown/tsdown/issues/286
N/A
> test: add tests for composite projects

- docs/zh-CN/guide/migrate-from-tsup.md
optimize the readability of migrate-from-tsup section.
> 优化“从 TSup 迁移”章节的可读性
Not sure if an update to English is necessary.
> docs:  optimize the readability of migrate-from-tsup section

- docs/options/config-file.md
- docs/zh-CN/options/config-file.md
Use a single import source across all guides for clarity and consistency.
I followed this guide, but Justineo still nitpicked me XD. https://github.com/ecomfe/vue-echarts/pull/847#discussion_r2252056700
> docs: unify defineConfig import path to 'tsdown'

- docs/guide/getting-started.md
- docs/zh-CN/guide/getting-started.md
Not sure what was the best phrasing, but we need clearer documentation about this.
Also do not forget to translate 🥹
Resolves #296
> docs: make manual installation clearer

- src/cli.ts
- src/options/index.ts
- src/options/types.ts
- src/utils/logger.ts
Added a `failOnWarn` option by making the logger throw on `warn()` and `warnOnce()`.
Not sure if the logger being responsible for throwing is the best way to handle this however 😕
Resolves #322
> feat: add failOnWarn option

- src/migrate.ts
Optimized the if-branches for `dependencies / devDependencies / peerDependencies` to avoid code duplication.
> refactor(migrate): optimize if-branches for dependency migration

- pnpm-lock.yaml
- src/features/rolldown.ts
- tests/__snapshots__/minify.snap.md
- tests/__snapshots__/without-hash-and-filename-conflict.snap.md
- tests/index.test.ts
`rolldown@1.0.0-beta.34` has removed the `resolve. tsconfigFilename` and use top-level `tsconfig` instead.
See: https://github.com/rolldown/rolldown/pull/5842/files#diff-c06074d6981cf90f9d47d528af94152edd3505a7244c70a7cfaabde4ce30e1f0
Related: https://github.com/rolldown/rolldown/issues/5839, https://github.com/rolldown/rolldown/pull/5842
> feat: support rolldown 1.0.0-beta.34

- docs/options/target.md
- docs/recipes/vue-support.md
- docs/zh-CN/options/target.md
- docs/zh-CN/recipes/vue-support.md
> docs: add `pnpm / yarn / bun` installation examples

- src/features/report.ts
This PR fixes #505.
(My first 'real' pr on a repo :flushed:)
Let me know if I missed anything!
> feat(report): add gzip option to control gzip compression reporting
